-- 1 - Retrieve the total number of rentals made in the Sakila database.
SELECT COUNT(*) AS total_rentals
FROM rental;

-- 2 - Find the average rental duration (in days) of movies rented from the Sakila database.
SELECT AVG(rental_duration) AS average_rental_duration
FROM film;
-- 3 - Display the first name and last name of customers in uppercase.
SELECT
    UPPER(first_name) AS first_name_upper,
    UPPER(last_name) AS last_name_upper
FROM customer;

-- 4 - Extract the month from the rental date and display it alongside the rental ID.
SELECT
    rental_id,
    MONTH(rental_date) AS rental_month
FROM rental;

-- 5. Retrieve the count of rentals for each customer (display customer ID and the count of rentals).

SELECT customer_id,count(*) AS total_rentals
FROM rental
group by customer_id;
-- 6 - Find the total revenue generated by each store.
SELECT
    store_id,
    SUM(amount) AS total_revenue
FROM payment
GROUP BY store_id;
-- 7 - Determine the total number of rentals for each category of movies.
SELECT
    c.name AS category_name,
    COUNT(r.rental_id) AS total_rentals
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
JOIN film_category fc ON f.film_id = fc.film_id
JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name;
-- 8 - Find the average rental rate of movies in each language.
SELECT
    l.name AS language_name,
    AVG(f.rental_rate) AS average_rental_rate
FROM film f
JOIN language l ON f.language_id = l.language_id
GROUP BY l.name;






